### ISSUE TITLE
Lunar Client Crash

### ISSUE THREAD

**Issue by DishieXD** [Nilsen84/lunar-client-qt#57] opened 2022-04-02 19:59 UTC
![Screenshot_7](https://user-images.githubusercontent.com/102878469/161399183-06bed6a6-31d7-4d81-abcc-91b48f87e992.png)
Tried old and new version, lunar client was closed, note: error crash code changes every time I try to launch

**Comment by Nilsen84** [comment] 2022-04-03 12:09
Just gonna close this because I'm not able to reproduce the crash and I have absolutely no idea what is causing it for you. Just make sure you're using the latest version of lcqt (1.2.5) and that lunar 1.7 is up to date.

**Closed by Nilsen84** 2022-04-03 12:09 UTC

**Comment by DishieXD** [comment] 2022-04-03 19:48
Yo quick update it works on 1.8 but not 1.7 just keeps crashing :(

**Comment by ItsPLMT** [comment] 2022-06-10 01:33
i play 1.18.2 lunar , but if i want to change my skin i press change but it crash and show Saving World

**Comment by lxchster** [comment] 2022-07-11 07:10
i had the same issue, i tried a bunch of things but fixed it by making a custom minecraft directory and copying all of the files over. yes it took ages but i think it fixed the issue. if that doesnt work, just try deleting the crash reports and other random files (idk if this does anything though).
